--DROP TABLE raw_data.load_info;

CREATE TABLE raw_data.load_info (
  id          bigint GENERATED BY DEFAULT AS IDENTITY,
  load_type   int NOT NULL,
  created_at  timestamptz DEFAULT clock_timestamp() NOT NULL,

  CONSTRAINT load_info_pk PRIMARY KEY (id),
  CONSTRAINT load_info_load_type_fk FOREIGN KEY (load_type) REFERENCES dict.load_type(id)
);

CREATE INDEX load_info_id_idx ON raw_data.load_info(id);


GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA raw_data TO bybitparser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA raw_data TO bybitparser;