CREATE TABLE raw_data.load_error_log (
  id                bigint GENERATED BY DEFAULT AS IDENTITY,
  load_id           bigint NOT NULL,
  created_at        timestamptz DEFAULT clock_timestamp() NOT NULL,
  error_description TEXT,
  
  CONSTRAINT load_error_log_pk PRIMARY KEY (id),
  CONSTRAINT load_error_log_load_fk FOREIGN KEY (load_id) REFERENCES raw_data.load_info(id)
);
GRANT INSERT ON TABLE raw_data.load_error_log TO bybitparser;