DROP TABLE raw_data.load_info;

CREATE TABLE raw_data.load_info (
  id          int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
  load_type   int                                   NOT NULL,
  created_at  timestamptz DEFAULT clock_timestamp() NOT NULL,
  
  CONSTRAINT load_info_pk PRIMARY KEY (id),
  CONSTRAINT load_info_load_type_fk FOREIGN KEY (load_type) REFERENCES dict.load_type(id)
);

CREATE INDEX load_info_id_idx ON raw_data.load_info(id);

GRANT INSERT ON TABLE raw_data.load_info TO bybitparser;
GRANT USAGE ON SEQUENCE raw_data.load_info_id_seq TO bybitparser;